apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: arquitetura-kanban
  namespace: arquitetura-kanban
  labels:
    app.kubernetes.io/name: arquitetura-kanban
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: arquitetura-kanban
